[package]
name = "hkrpg-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

[lib]
name = "hkrpg_api"
path = "src/lib.rs"

[profile.release]
strip = true
lto = true
opt-level = 3
codegen-units = 1